name: puzzle
description: A new Flutter application.

# The following defines the version and build number for your application.
version: 1.0.0+12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
#  rxdart: ^0.22.1+1
  rxdart: ^0.22.2
  shared_preferences: ^0.5.3+4
  audioplayers: ^0.13.1
  image_picker: ^0.6.1+3
  firebase_storage: ^3.0.6
  transparent_image: ^0.1.0
  cloud_firestore: ^0.12.9+4
  cached_network_image: ^1.1.1
  rflutter_alert: ^1.0.3
  country_pickers: ^1.1.0
  fireworks: ^0.9.3
  button3d: ^0.1.0
  flutter_swiper: ^1.1.6
  firebase_admob: ^0.9.0+7
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/audio/swap.wav
    - assets/audio/win.wav
    - assets/audio/press.wav
    - assets/audio/start.wav
    - assets/locale/locale_en.json
    - assets/locale/locale_vi.json
    - assets/images/tips.jpg
    - assets/images/guide.png
  fonts:
    - family: vt323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf
          style: italic

